# Generated by Django 5.0 on 2024-11-14 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="owner_user_ids",
            field=models.ManyToManyField(related_name="owner_surveys", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="survey",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="user_response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="survey.userresponse",
            ),
        ),
        migrations.AlterField(
            model_name="userresponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answeroption",
            unique_together={("question", "seq_id")},
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("survey", "seq_id")},
        ),
        migrations.AddIndex(
            model_name="answeroption",
            index=models.Index(
                fields=["question", "seq_id"], name="survey_answ_questio_b4cb40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["survey", "seq_id"], name="survey_ques_survey__8673b2_idx"),
        ),
    ]
