# Generated by Django 5.0 on 2024-12-03 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0003_alter_useranswer_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswer",
            name="user_response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="survey.userresponse",
            ),
        ),
    ]
