# Generated by Django 5.0 on 2024-12-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0004_alter_useranswer_user_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answeroption",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="survey",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
