# Generated by Django 5.0 on 2025-01-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0005_alter_answeroption_name_alter_question_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answeroption",
            name="name",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="question",
            name="name",
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
