# Generated by Django 5.0 on 2025-02-19 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0006_alter_answeroption_name_alter_question_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answeroption",
            options={"ordering": ["seq_id"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["seq_id"]},
        ),
    ]
