# Generated by Django 5.0 on 2025-04-04 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0008_alter_userresponse_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="notificate",
        ),
    ]
